import operator
import os
from pathlib import Path
from typing import Annotated

from dotenv import load_dotenv
from langchain_core.messages import HumanMessage, SystemMessage
from langchain_openai import ChatOpenAI
from langgraph.types import Send
from langgraph.graph import END, START, StateGraph
from pydantic import BaseModel, Field
from typing_extensions import TypedDict


ROOT = Path(__file__).parent
DASHSCOPE_BASE_URL = "https://dashscope.aliyuncs.com/compatible-mode/v1"


class TaskPlan(BaseModel):
    """Plan generated by the orchestrator."""

    tasks: list[str] = Field(description="3 to 4 concrete subtasks for worker agents.")


class OverallState(TypedDict):
    """State shared by the whole orchestrator-workers workflow."""

    topic: str
    tasks: list[str]
    worker_results: Annotated[list[str], operator.add]
    final_answer: str


class WorkerState(TypedDict):
    """State received by each worker."""

    task: str


def build_model() -> ChatOpenAI:
    load_dotenv(ROOT.parent / ".env", encoding="utf-8-sig")

    api_key = os.getenv("DASHSCOPE_API_KEY")
    if not api_key:
        raise RuntimeError("Missing DASHSCOPE_API_KEY. Please fill it in D:\\code\\agent\\LangGraph\\.env")

    return ChatOpenAI(
        model="qwen-plus",
        api_key=api_key,
        base_url=DASHSCOPE_BASE_URL,
    )


model = build_model()
planner_model = model.with_structured_output(TaskPlan)


def orchestrator(state: OverallState) -> dict[str, list[str]]:
    """Node 1: split a complex request into smaller worker tasks."""
    plan = planner_model.invoke([
        SystemMessage(
            content=(
                "你是一个 Agent 总控调度器。你的任务不是直接回答用户，"
                "而是把用户的复杂学习目标拆成 3 个清晰、可执行的子任务。\n"
                "要求：\n"
                "1. 每个子任务必须具体。\n"
                "2. 子任务之间尽量互补，不要重复。\n"
                "3. 只输出结构化 tasks。"
            )
        ),
        HumanMessage(content=f"学习目标：{state['topic']}"),
    ])
    return {"tasks": plan.tasks[:3]}


def assign_workers(state: OverallState) -> list[Send]:
    """Conditional edge: send every task to a worker."""
    return [Send("worker", {"task": task}) for task in state["tasks"]]


def worker(state: WorkerState) -> dict[str, list[str]]:
    """Node 2: solve one subtask."""
    response = model.invoke([
        SystemMessage(
            content=(
                "你是一个学习助教 worker。你只负责完成分配给你的一个子任务。"
                "请用中文输出，要求简洁、准确、适合初学者。"
            )
        ),
        HumanMessage(content=state["task"]),
    ])
    result = f"子任务：{state['task']}\n结果：{response.content}"
    return {"worker_results": [result]}


def aggregator(state: OverallState) -> dict[str, str]:
    """Node 3: merge worker outputs into one final answer."""
    joined_results = "\n\n".join(state["worker_results"])
    response = model.invoke([
        SystemMessage(
            content=(
                "你是一个内容汇总专家。请把多个 worker 的结果整合成一份完整学习笔记。\n"
                "要求：\n"
                "1. 先给出学习主题。\n"
                "2. 按知识点分段。\n"
                "3. 最后给出 3 条下一步练习建议。\n"
                "4. 不要编造 worker 没有提供的信息。"
            )
        ),
        HumanMessage(content=f"学习主题：{state['topic']}\n\nworker 输出：\n{joined_results}"),
    ])
    return {"final_answer": response.content}


def build_graph():
    builder = StateGraph(OverallState)

    builder.add_node("orchestrator", orchestrator)
    builder.add_node("worker", worker)
    builder.add_node("aggregator", aggregator)

    builder.add_edge(START, "orchestrator")
    builder.add_conditional_edges("orchestrator", assign_workers, ["worker"])
    builder.add_edge("worker", "aggregator")
    builder.add_edge("aggregator", END)

    return builder.compile()


def main() -> None:
    graph = build_graph()

    topic = "我想快速入门 LangGraph，并理解它和普通 LangChain 调用有什么区别"
    result = graph.invoke({
        "topic": topic,
        "tasks": [],
        "worker_results": [],
        "final_answer": "",
    })

    print("=" * 80)
    print("用户学习目标：")
    print(topic)

    print("\n" + "=" * 80)
    print("总控拆出来的子任务：")
    for index, task in enumerate(result["tasks"], start=1):
        print(f"{index}. {task}")

    print("\n" + "=" * 80)
    print("worker 分别完成的结果：")
    for index, worker_result in enumerate(result["worker_results"], start=1):
        print(f"\n--- Worker {index} ---")
        print(worker_result)

    print("\n" + "=" * 80)
    print("汇总后的最终学习笔记：")
    print(result["final_answer"])


if __name__ == "__main__":
    main()

